# Generated by Django 2.2.7 on 2019-11-23 14:01

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Map', max_length=256)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('geom', djgeojson.fields.PointField()),
                ('daymap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.DayMap')),
            ],
        ),
    ]
