# Generated by Django 2.2.7 on 2019-11-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetspot',
            name='daymap',
        ),
    ]
