# Generated by Django 2.2.7 on 2019-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayMap',
        ),
        migrations.RemoveField(
            model_name='tweetspot',
            name='description',
        ),
        migrations.AddField(
            model_name='query',
            name='est_mun',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetspot',
            name='coe_sent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetspot',
            name='qt_tweets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
